# proot-distro build -f Dockerfile.cn -t alas-cn-arm64:latest .

FROM docker.1ms.run/python:3.7-slim-bullseye

EXPOSE 22267

WORKDIR /app/AzurLaneAutoScript

RUN echo "\
    deb https://mirrors.aliyun.com/debian/ bullseye main non-free contrib\n\
    deb-src https://mirrors.aliyun.com/debian/ bullseye main non-free contrib\n\
    deb https://mirrors.aliyun.com/debian-security/ bullseye-security main\n\
    deb-src https://mirrors.aliyun.com/debian-security/ bullseye-security main\n\
    deb https://mirrors.aliyun.com/debian/ bullseye-updates main non-free contrib\n\
    deb-src https://mirrors.aliyun.com/debian/ bullseye-updates main non-free contrib" \
    > /etc/apt/sources.list \
    && apt update \
    && apt install -y git adb libgomp1 openssh-client \
    && apt install -y build-essential pkg-config \
    && apt install -y libavformat-dev libavcodec-dev libavdevice-dev \
    && apt install -y libavutil-dev libswscale-dev libswresample-dev libavfilter-dev \
    # 外部mxnet所需依赖
    && apt install -y libatlas3-base libopencv-imgcodecs4.5 \
    && git config --global --add safe.directory '*' \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo 'Asia/Shanghai' > /etc/timezone \
    && pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple \
    && pip install --no-cache-dir Cython==0.29.37 \
    && pip install --no-cache-dir av==10.0.0 --no-build-isolation \
    # 清理缓存
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

# 用于打破缓存，强制重新执行以下命令，用法：proot-distro build --build-arg UPDATECODE=$SHA
ARG UPDATECODE=0

COPY requirements.txt /tmp/requirements.txt

# 国内使用项目中的文件安装，避免url访问失败
RUN pip install --no-cache-dir -r /tmp/requirements.txt && rm -f /tmp/requirements.txt

# 后置安装外部mxnet包，解决冲突问题(国内源)
# 新的Layer层，避免下载失败导致整层重下，出错再次构建可复用之前的缓存
RUN pip install --no-cache-dir https://binsitepublic-10018028.file.myqcloud.com/mxnet-1.9.1-py3-none-any.whl \
    # 软链接解决找不到libmxnet.so问题
    && ln -s /usr/local/mxnet/libmxnet.so /usr/local/lib/python3.7/site-packages/mxnet/libmxnet.so

CMD ["python", "gui.py"]
