#docker build -f Dockerfile.full -t alas-full-amd64:latest .

FROM ghcr.io/qingmingtd/alas-amd64:latest

EXPOSE 22267

WORKDIR /app

# 用于打破缓存，强制重新执行以下命令
ARG UPDATECODE=0

RUN git clone --depth 1 https://github.com/LmeSzinc/AzurLaneAutoScript.git

CMD ["python", "AzurLaneAutoScript/gui.py"]