# docker build -f Dockerfile.cn -t alas-cn-amd64:latest .

FROM python:3.7-slim-bullseye

EXPOSE 22267

WORKDIR /app/AzurLaneAutoScript

RUN echo "\
    deb https://mirrors.aliyun.com/debian/ bullseye main non-free contrib\n\
    deb-src https://mirrors.aliyun.com/debian/ bullseye main non-free contrib\n\
    deb https://mirrors.aliyun.com/debian-security/ bullseye-security main\n\
    deb-src https://mirrors.aliyun.com/debian-security/ bullseye-security main\n\
    deb https://mirrors.aliyun.com/debian/ bullseye-updates main non-free contrib\n\
    deb-src https://mirrors.aliyun.com/debian/ bullseye-updates main non-free contrib" \
    > /etc/apt/sources.list \
    && apt update \
    && apt install -y git adb libgomp1 openssh-client \
    && apt install -y build-essential pkg-config \
    && apt install -y libavformat-dev libavcodec-dev libavdevice-dev \
    && apt install -y libavutil-dev libswscale-dev libswresample-dev libavfilter-dev \
    && git config --global --add safe.directory '*' \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo 'Asia/Shanghai' > /etc/timezone \
    && pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple \
    && pip install --no-cache-dir Cython==0.29.37 \
    && pip install --no-cache-dir av==10.0.0 --no-build-isolation \
    # 清理缓存
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

# 用于打破缓存，强制重新执行以下命令，用法：docker build --build-arg UPDATECODE=$SHA
ARG UPDATECODE=0

COPY requirements.txt /tmp/requirements.txt

# 国内使用项目中的文件安装，避免url访问失败
RUN pip install --no-cache-dir -r /tmp/requirements.txt && rm -f /tmp/requirements.txt

CMD ["python", "gui.py"]
