
# =========================
# Builder 阶段
# =========================
# 国内镜像
FROM docker.1ms.run/python:3.7-slim-bullseye AS builder

# 国内apt源，安装开发工具，编译av包
RUN echo "\
    deb https://mirrors.aliyun.com/debian/ bullseye main non-free contrib\n\
    deb-src https://mirrors.aliyun.com/debian/ bullseye main non-free contrib\n\
    deb https://mirrors.aliyun.com/debian-security/ bullseye-security main\n\
    deb-src https://mirrors.aliyun.com/debian-security/ bullseye-security main\n\
    deb https://mirrors.aliyun.com/debian/ bullseye-updates main non-free contrib\n\
    deb-src https://mirrors.aliyun.com/debian/ bullseye-updates main non-free contrib" \
    > /etc/apt/sources.list \
    && apt update \
    && apt install -y build-essential pkg-config \
    && apt install -y libavformat-dev libavcodec-dev libavdevice-dev \
    && apt install -y libavutil-dev libswscale-dev libswresample-dev libavfilter-dev \
    # 配置pip镜像源
    && pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple \
    && pip install --no-cache-dir Cython==0.29.37 \
    && pip install --no-cache-dir av==10.0.0 --no-build-isolation \
    # 清理缓存
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

# 用于打破缓存，强制重新执行以下命令，用法：docker build --build-arg UPDATECODE=$SHA
ARG UPDATECODE=0

# 国内使用项目中的文件安装，解决url访问失败
COPY requirements.txt /tmp/requirements.txt
# 安装python依赖
RUN pip install --no-cache-dir -r /tmp/requirements.txt && rm -f /tmp/requirements.txt

# =========================
# Runtime 阶段
# =========================
# 国内镜像
FROM docker.1ms.run/python:3.7-slim-bullseye

EXPOSE 22267

WORKDIR /app/AzurLaneAutoScript

RUN echo "\
    deb https://mirrors.aliyun.com/debian/ bullseye main non-free contrib\n\
    deb-src https://mirrors.aliyun.com/debian/ bullseye main non-free contrib\n\
    deb https://mirrors.aliyun.com/debian-security/ bullseye-security main\n\
    deb-src https://mirrors.aliyun.com/debian-security/ bullseye-security main\n\
    deb https://mirrors.aliyun.com/debian/ bullseye-updates main non-free contrib\n\
    deb-src https://mirrors.aliyun.com/debian/ bullseye-updates main non-free contrib" \
    > /etc/apt/sources.list \
    && apt update \
    # 基础工具
    && apt install -y git adb openssh-client \
    # 依赖库
    && apt install -y libgomp1 \
    && git config --global --add safe.directory '*' \
    # 配置时区
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo 'Asia/Shanghai' > /etc/timezone \
    # 清理缓存
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder \
    /usr/local/lib/python3.7/site-packages \
    /usr/local/lib/python3.7/site-packages

CMD ["python", "gui.py"]
